const CONFIG = {
  name:        "Lily Feng",
  initials:    "LF",
  title:       "Oracle ERP Engineer",
  org:         "IEI Integration Corp.",
  email:       "lily103lily@gmail.com",
  linkedinUrl: "https://www.linkedin.com/in/lily-feng-baa971107/",
  githubUrl:   "https://github.com/lily103lily",
  instagramUrl:  "https://www.instagram.com/lilyfeng_tw/",
  blogUrl:       "https://lily103lily.pixnet.net/blog",
  lineStickerUrl:"https://store.line.me/stickershop/author/5367856/zh-Hant",
  redbubbleUrl:  "https://lilyfeng.redbubble.com",
  pageUrl:     "https://lily103lily.github.io/about-me",
  vcfFile:     "lily.vcf",
  vcfDownload: "Lily_Feng.vcf",
};
