const CONFIG = {
  name:        "Lily Feng",
  initials:    "LF",
  title:       "Oracle ERP Engineer",
  org:         "IEI Integration Corp.",
  email:       "lily103lily@gmail.com",
  linkedinUrl: "#",
  githubUrl:   "https://github.com/lily103lily",
  instagramUrl:  "#",
  blogUrl:       "#",
  lineStickerUrl:"#",
  redbubbleUrl:  "#",
  pageUrl:     "https://lily103lily.github.io/about-me",
  vcfFile:     "lily.vcf",
  vcfDownload: "Lily_Feng.vcf",
};
